project:
  type: website
  output-dir: docs
  resources:
    - files/resume.pdf
  
website:
  title: "Shawkat Ali"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/shawkatrony84/my_website
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Shawkat Ali"

format:
  html:
    theme: cerulean
    toc: true

editor: source

